adding stop when errors

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,12 +22,13 @@ jobs:
         run: |
               while read -r arr
               do
-                  IFS=':';
-                  read -a line <<< $arr
-                  echo "::error file=${line[0]},line=${line[1]},title=${line[2]}::${line[3]}"
-              done < "coding-style-reports.log"
-
-    ## fail job if coding style errors
+                IFS=':'; read -a line <<< $arr; echo "::error file=${line[0]},line=${line[1]},title=${line[2]}::${line[3]}"
+              done < "coding-style-checker/coding-style-reports.log"
+              cat coding-style-checker/coding-style-reports.log | grep -q :
+              if [ $? -eq 0 ]
+              then
+                exit 1
+              fi
 
   check_program_compilation:
     needs: check_coding_style
@@ -44,8 +45,7 @@ jobs:
         run: make clean
       - name: check_executables
         run: |
-              IFS=',';
-              read -a arr <<< "$EXECUTABLES";
+              IFS=','; read -a arr <<< "$EXECUTABLES";
               for i in "${arr[@]}"
                 do
                   ls -R | grep -x "$i";
