adding an extra step to see if there is errors

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -19,16 +19,21 @@ jobs:
       - name: run_coding_style_checker
         run: check.sh $PWD $PWD
       - name: check_coding_style_report
+        id: check_coding_style_report
+        run: |
+          cat coding-style-checker/coding-style-reports.log | grep -q :
+          if [ $? -eq 0 ]
+          then
+            echo "CODING_STYLE_ERRORS=there_is" >> $GITHUB_OUTPUT
+          fi
+      - name: coding_style_errors
+        if: ${{ steps.check_coding_style_report.outputs.CODING_STYLE_ERRORS == 'there_is' }}
         run: |
               while read -r arr
               do
                 IFS=':'; read -a line <<< $arr; echo "::error file=${line[0]},line=${line[1]},title=${line[2]}::${line[3]}"
               done < "coding-style-reports.log"
-              cat coding-style-reports.log | grep -q :
-              if [ $? -eq 0 ]
-              then
-                exit 1
-              fi
+              exit 1
 
   check_program_compilation:
     needs: check_coding_style
