modifing test_executables for less lines

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -54,10 +54,11 @@ jobs:
               read -a arr <<< "$EXECUTABLES";
               for i in "${arr[@]}"
                 do
-                  ls -R | grep -x "$i";
-                  if [ $? -eq 1 ]
-                  then
-                    exit 1
+                  if [ -f $i ]; then
+                    echo
+                  else
+                    echo "::error title=Missing::$i"
+                    exit 1;
                   fi
                 done
   run_tests:
